version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: simple-bookkeeping-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-simple_bookkeeping}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - simple-bookkeeping-network
    # PostgreSQLポートは外部に公開しない（内部ネットワークのみ）

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: simple-bookkeeping-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-simple_bookkeeping}?schema=public
      API_PORT: ${API_PORT:-3001}
      NODE_ENV: ${NODE_ENV:-development}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-1h}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-super-secret-refresh-key-change-this-in-production}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
    ports:
      - '${API_PORT:-3001}:${API_PORT:-3001}'
    networks:
      - simple-bookkeeping-network
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/api/node_modules

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: simple-bookkeeping-web
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001/api/v1}
    ports:
      - '${WEB_PORT:-3000}:3000'
    networks:
      - simple-bookkeeping-network
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/web/node_modules

volumes:
  postgres_data:

networks:
  simple-bookkeeping-network:
    driver: bridge
