[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm-8"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @simple-bookkeeping/api build"]

[start]
cmd = "cd apps/api && node dist/index.js"