[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm && pnpm install --filter @simple-bookkeeping/api... && pnpm --filter @simple-bookkeeping/api build"

[deploy]
startCommand = "cd apps/api && node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30