services:
  - type: web
    name: simple-bookkeeping-api
    runtime: node
    plan: free # 無料プランを明示的に指定
    region: singapore
    buildCommand: pnpm install --prod=false && cd packages/database && npx prisma generate && npx prisma migrate deploy && cd ../.. && pnpm --filter @simple-bookkeeping/database build && pnpm --filter @simple-bookkeeping/core build && pnpm --filter @simple-bookkeeping/shared build && pnpm --filter @simple-bookkeeping/api build
    startCommand: cd apps/api && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: simple-bookkeeping-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: CORS_ORIGIN
        value: https://simple-bookkeeping-kens-projects-924cd1a9.vercel.app

databases:
  - name: simple-bookkeeping-db
    plan: free
    region: singapore
    databaseName: simple_bookkeeping
    user: simple_bookkeeping_user
