name: 📚 ドキュメント
description: ドキュメントの追加・更新・修正
title: '[Doc]: '
labels: ['documentation']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ドキュメントの改善提案ありがとうございます！より分かりやすいプロジェクトにするためのご協力に感謝します。

  - type: dropdown
    id: doc-type
    attributes:
      label: ドキュメントの種類
      description: どの種類のドキュメントですか？
      options:
        - README
        - API仕様書
        - 開発ガイド
        - ユーザーマニュアル
        - アーキテクチャ設計書
        - コメント・JSDoc
        - その他
    validations:
      required: true

  - type: dropdown
    id: action
    attributes:
      label: アクション
      description: 何を行いますか？
      options:
        - 新規作成
        - 内容の更新
        - 誤字・脱字の修正
        - 構成の改善
        - 翻訳
    validations:
      required: true

  - type: textarea
    id: target-file
    attributes:
      label: 対象ファイル
      description: 変更するドキュメントファイルのパスを記載してください
      placeholder: |
        例：
        - docs/api/README.md
        - README.md
        - CONTRIBUTING.md
        - 新規作成: docs/deployment/render-setup.md
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 変更理由
      description: なぜこのドキュメントの変更が必要ですか？
      placeholder: |
        例：新しく追加された機能についての説明が不足しており、
        開発者が実装方法を理解するのに時間がかかっている。
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: 変更内容
      description: 具体的にどのような変更を行いますか？
      placeholder: |
        例：
        1. インストール手順の更新（pnpm対応）
        2. 環境変数の説明を追加
        3. トラブルシューティングセクションを新設
        4. コード例を最新のAPIに合わせて更新
    validations:
      required: true

  - type: textarea
    id: outline
    attributes:
      label: 目次・構成案
      description: 新規作成または大幅な変更の場合、構成案を記載してください
      placeholder: |
        例：
        # デプロイメントガイド
        ## 1. 前提条件
        ## 2. Renderの設定
        ## 3. 環境変数の設定
        ## 4. デプロイ手順
        ## 5. トラブルシューティング
        ## 6. よくある質問

  - type: dropdown
    id: audience
    attributes:
      label: 対象読者
      description: このドキュメントの主な読者は誰ですか？
      multiple: true
      options:
        - 開発者（コントリビューター）
        - システム管理者
        - エンドユーザー
        - プロジェクトマネージャー
        - デザイナー
        - すべて
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 参考資料
      description: 参考にした資料やリンクがあれば記載してください
      placeholder: |
        例：
        - [Playwright公式ドキュメント](https://playwright.dev/)
        - 社内Wiki: http://example.com/wiki
        - 関連Issue: #95

  - type: textarea
    id: review-points
    attributes:
      label: レビューポイント
      description: 特に確認してほしい点があれば記載してください
      placeholder: |
        例：
        - 技術的な正確性
        - 用語の統一性
        - 初心者にも分かりやすいか

  - type: textarea
    id: additional
    attributes:
      label: その他
      description: その他、関連する情報があれば記載してください

  - type: checkboxes
    id: checklist
    attributes:
      label: チェックリスト
      description: 以下の項目を確認してください
      options:
        - label: 既存のドキュメントと重複していないことを確認しました
          required: true
        - label: 技術的な正確性を確認しました
          required: false
        - label: リンクが正しく機能することを確認しました
          required: false
        - label: コード例が動作することを確認しました
          required: false
