#!/bin/bash
# Render deployment script using git push

echo "🚀 Render デプロイメント（Git Push方式）"
echo "========================================"
echo ""
echo "RenderはGitHubとの連携により自動デプロイされます。"
echo ""
echo "📋 セットアップ手順："
echo ""
echo "1. Render Dashboardにアクセス"
echo "   https://dashboard.render.com"
echo ""
echo "2. 「New +」→「Blueprint」をクリック"
echo ""
echo "3. GitHubリポジトリを選択:"
echo "   - knishioka/simple-bookkeeping"
echo ""
echo "4. render.yamlが自動検出されます"
echo ""
echo "5. 「Apply」をクリックしてデプロイ開始"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "または、既存のサービスがある場合は："
echo ""
echo "# 最新のコードをプッシュして再デプロイ"
echo "git add ."
echo "git commit -m 'Trigger Render deployment'"
echo "git push origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 render.yamlの内容："
cat render.yaml
echo ""